name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    # Only enable Windows VS2022 for now
    name: Windows VS2022 Static
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform:
        # Only need VS2022 CI checks due to Windows.h platform specificity
        - { name: Windows VS2022, os: windows-2022 }
        # - { name: Windows VS2019, os: windows-2019  }
        # - { name: Linux GCC,      os: ubuntu-latest }
        # - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        # - { name: macOS,          os: macos-latest  }
        config:
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }
        # - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build ${{ matrix.platform.flags }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config Release
